### ISSUE TITLE
Extemely slow

### ISSUE THREAD

**Issue by ghost** [xerpi/psp-uvc-usb-video-class#5]
When streaming the video source to v4l2 framerate drops down to 18-20 fps on PSP GO 6.61 CFW PRO
Because of this the psp is unable to connect to wifi services or open audio and video files.

**Comment by xerpi** [comment]
Check the description here: https://github.com/xerpi/psp-uvc-usb-video-class/releases/tag/0.1

**Comment by ghost** [comment]
I see,will further optimizations improve usability or is the PSP's hardware the limiting factor on the amount is can render?
